spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_AUTH}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true